export const teamFlags = {
    Algeria: "🇩🇿",
    Argentina: "🇦🇷",
    Australia: "🇦🇺",
    Austria: "🇦🇹",
    Belgium: "🇧🇪",
    "Bosnia-Herzegovina":"🇧🇦",
    Brazil: "🇧🇷",
    Canada: "🇨🇦",
    "Cape Verde Islands": "🇨🇻",
    Curaçao: "🇨🇼",
    Colombia: "🇨🇴",
    "Congo DR": "🇨🇩",
    Croatia: "🇭🇷",
    Czechia: "🇨🇿",
    Ecuador: "🇪🇨",
    Egypt: "🇪🇬",
    England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    France: "🇫🇷",
    Germany: "🇩🇪",
    Ghana: "🇬🇭",
    Haiti: "🇭🇹",
    Iran: "🇮🇷",
    "Ivory Coast": "🇨🇮",
    Japan: "🇯🇵",
    Mexico: "🇲🇽",
    Morocco: "🇲🇦",
    Netherlands: "🇳🇱",
    "New Zealand": "🇳🇿",
    Norway: "🇳🇴",
    Paraguay: "🇵🇾",
    Iraq: "🇮🇶",
    Jordan: "🇯🇴",
    Portugal: "🇵🇹",
    Qatar: "🇶🇦",
    "Saudi Arabia": "🇸🇦",
    Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    Senegal: "🇸🇳",
    Panama: "🇵🇦",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    Spain: "🇪🇸",
    Sweden: "🇸🇪",
    Switzerland: "🇨🇭",
    Tunisia: "🇹🇳",
    Turkey: "🇹🇷",
    Uzbekistan: "🇺🇿",
    Uruguay: "🇺🇾",
    "United States": "🇺🇸",
};

export const getTeamFlag = (teamName) => {
    return teamFlags[teamName] || "🏳️";
};