export const teamISOCodes = {
    Algeria: "dz",
    Argentina: "ar",
    Australia: "au",
    Austria: "at",
    Belgium: "be",
    "Bosnia-Herzegovina": "ba",
    Brazil: "br",
    Canada: "ca",
    "Cape Verde Islands": "cv",
    Curaçao: "cw",
    Colombia: "co",
    "Congo DR": "cd",
    Croatia: "hr",
    Czechia: "cz",
    Ecuador: "ec",
    Egypt: "eg",
    England: "gb-eng",
    France: "fr",
    Germany: "de",
    Ghana: "gh",
    Haiti: "ht",
    Iran: "ir",
    "Ivory Coast": "ci",
    Japan: "jp",
    Mexico: "mx",
    Morocco: "ma",
    Netherlands: "nl",
    "New Zealand": "nz",
    Norway: "no",
    Paraguay: "py",
    Iraq: "iq",
    Jordan: "jo",
    Portugal: "pt",
    Qatar: "qa",
    "Saudi Arabia": "sa",
    Scotland: "gb-sct",
    Senegal: "sn",
    Panama: "pa",
    "South Africa": "za",
    "South Korea": "kr",
    Spain: "es",
    Sweden: "se",
    Switzerland: "ch",
    Tunisia: "tn",
    Turkey: "tr",
    Uzbekistan: "uz",
    Uruguay: "uy",
    "United States": "us",
};

export const getTeamFlagUrl = (teamName) => {
    const code = teamISOCodes[teamName];
    if (!code) return null;
    return `https://flagcdn.com/w40/${code}.png`;
};
